export const members = [
    {
      member: { name: "Alice Johnson", email: "alice.johnson@example.com" },
      company: "TechCorp Solutions",
      role: "Senior Product Manager",
      location: "San Francisco, CA",
      expertise: "Product Management",
      status: "active",
    },
    {
      member: { name: "Bob Smith", email: "bob.smith@example.com" },
      company: "InnovateX",
      role: "Lead Software Engineer",
      location: "New York, NY",
      expertise: "User Experience",
      status: "active",
    },
    {
      member: { name: "Carol Lee", email: "carol.lee@example.com" },
      company: "FutureSoft",
      role: "UX Designer",
      location: "Austin, TX",
      expertise: "User Experience",
      status: "inactive",
    },
    {
      member: { name: "David Kim", email: "david.kim@example.com" },
      company: "NextGen Labs",
      role: "Product Owner",
      location: "Seattle, WA",
      expertise: "Product Management",
      status: "active",
    },
    {
      member: { name: "Eva Martinez", email: "eva.martinez@example.com" },
      company: "BrightTech",
      role: "Senior UX Researcher",
      location: "Boston, MA",
      expertise: "User Experience",
      status: "active",
    },
    {
      member: { name: "Frank Wilson", email: "frank.wilson@example.com" },
      company: "InnovateX",
      role: "Software Engineer",
      location: "Denver, CO",
      expertise: "Product Management",
      status: "inactive",
    },
    {
      member: { name: "Grace Chen", email: "grace.chen@example.com" },
      company: "TechCorp Solutions",
      role: "Product Manager",
      location: "San Francisco, CA",
      expertise: "Product Management",
      status: "active",
    },
    {
      member: { name: "Henry Patel", email: "henry.patel@example.com" },
      company: "NextGen Labs",
      role: "UX Designer",
      location: "Seattle, WA",
      expertise: "User Experience",
      status: "active",
    },
    {
      member: { name: "Isabel Gomez", email: "isabel.gomez@example.com" },
      company: "BrightTech",
      role: "Product Manager",
      location: "Boston, MA",
      expertise: "Product Management",
      status: "inactive",
    },
    {
      member: { name: "Jack Brown", email: "jack.brown@example.com" },
      company: "FutureSoft",
      role: "Lead UX Designer",
      location: "Austin, TX",
      expertise: "User Experience",
      status: "active",
    },
  ];
  